services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: trend-to-rule-app
    env_file:
      - ./src/.env
    ports:
      - "8501:8501"
    volumes:
      - ./.data:/app/.data
    restart: unless-stopped
